version: "3"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:  # Named volumes: se guardan en el host.. en una ruta que controla docker... no yo...
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  # Estoy configurando por algun lao la carpeta que quiero a nivel del host?
  # Esto se hace para 2 propositos... y ninguno que nos intere a nosotros.
  # - Compartir datos entre contenedores
  # - Cuando monto un fichero docker-compose genérico que tengo que asegurar que pueda correr sin cambios en cualquier host.  
  
  # Para qué sirven los volúmenes:
  # - Persistir datos tras borrado del contenedor
  # - Inyectar datos al contenedor
  # - Compartir datos entre contenedores
  # - Los datos los quiero poder tener accesibles desde fuera: BACKUPS