version: "3"

services:
    sonar:  # FQDN resoluble a nivel del DNS interno de Docker... 
            # para referirme dentro de la red de docker a este contenedor mediante un nombre y no su IP.
        container_name: sonarqube # Este es el nombre del contenedor... Lo que uso con el comando DOCKER para referirme al contenedor
        image:          sonarqube:10.5-community
        depends_on:
                      - bbdd
        ports:
                      - 8080:9000
        environment:
                      - SONAR_JDBC_URL=jdbc:postgresql://bbdd:5432/usuario
                      - SONAR_JDBC_USERNAME=usuario
                      - SONAR_JDBC_PASSWORD=password
        volumes:
                      - /home/ubuntu/environment/data/sonar/core:/opt/sonarqube/data
                      - /home/ubuntu/environment/data/sonar/extensions:/opt/sonarqube/extensions
                      - /home/ubuntu/environment/data/sonar/logs:/opt/sonarqube/logs
    bbdd:
        container_name: mi-postgre-sql
        image:          postgres:12
        environment:
                        POSTGRES_PASSWORD:  password
                        POSTGRES_USER:      usuario
        volumes:
                      - /home/ubuntu/environment/data/postgresql/data:/var/lib/postgresql/data
                      - /home/ubuntu/environment/data/postgresql/core:/var/lib/postgresql
#volumes: