services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    user: root
    volumes:
      - /var/jenkins_home:/var/jenkins_home
        # DiD: Docker In Docker
      - /usr/bin/docker:/usr/bin/docker # Le paso al contenedor de jenkins, el comando "docker" que tengo en el host
      - /var/run/docker.sock:/var/run/docker.sock # Le paso el socket de conexión al servicio de docker
