version: "3"

services: # Aqui declaro los contenedores
    maven:
        image:          maven:3.8.5-openjdk-18
        volumes: 
            -           /home/ubuntu/environment/curso/proyectos/proyecto:/proyecto
        working_dir:    /proyecto
        command:        [mvn, package]

# Cu치l es la primera ventaja de tener un fichero, en lugar de un comando?
# El fichero va a control de versi칩n... GIT
# Y quiero compartirlo f치cil con mis compa침eros